### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by junrushao**
A minor C++ syntax error. Seems introduced by https://github.com/mlc-ai/mlc-llm/pull/1007

### CODE REVIEW

**Comment by junrushao** [comment]
CC: @tqchen
